// Reviewed bilingual source specifications for the Phase-2 PYQ workflow pack.
// AUD-D3 / AUD-F4: source-bound JEE workflows with explicit output formats.
// This file is data only. Run build-pyq-workflows.mjs to create merge-ready JSON.

export const CATEGORY = {
  category: 'pyq-workflows',
  categoryTitle: 'PYQ Power Workflows',
  categoryIcon: '🧾',
  group: 'Practice & Assessment',
  categoryBlurb: 'Turn teacher-pasted real past questions into source-honest analysis, marking, drills and discussion without inventing provenance, trends or current-pattern claims.',
};

const REVIEWED_CANDIDATES = [
  {
    title: 'Five ORIGINAL PRACTICE Variants from One Pasted PYQ',
    titleHi: 'एक पेस्ट किए PYQ से पाँच ORIGINAL PRACTICE रूपांतर',
    tag: 'Five Safe Variants', fmt: 'doc', aud: 'teacher', extraInput: '[ALLOWED VALUE RANGES AND EXCLUSIONS]',
    whatYouGet: 'Five same-difficulty, structurally faithful practice variants derived only from one teacher-pasted past question, with a separate checked key and an unmistakable ORIGINAL PRACTICE label.',
    whatYouGetHi: 'केवल शिक्षक द्वारा पेस्ट किए गए एक पिछले प्रश्न से बने समान कठिनाई और समान गणितीय संरचना वाले पाँच अभ्यास-रूपांतर, अलग जाँची गई उत्तर-कुंजी और स्पष्ट ORIGINAL PRACTICE चिह्न के साथ।',
    howToUse: 'Paste the complete question, its teacher-supplied source label and any known answer; set the allowed variation limits before reviewing every new item.',
    howToUseHi: 'पूरा प्रश्न, शिक्षक द्वारा दिया स्रोत-चिह्न और उपलब्ध उत्तर पेस्ट करें; हर नए प्रश्न की समीक्षा से पहले स्वीकार्य बदलाव की सीमाएँ तय करें।',
    commonFix: 'If the variants drift, ask the AI to restate the invariant method, discard every changed-skill item and rebuild only inside the supplied limits.',
    commonFixHi: 'यदि रूपांतर लक्ष्य से हटें, तो AI से अपरिवर्तित विधि दोबारा लिखवाएँ, कौशल बदलने वाला हर प्रश्न हटाएँ और केवल दी गई सीमाओं के भीतर फिर बनाएँ।',
    role: 'Act as a source-bound JEE practice designer and variant auditor.',
    roleHi: 'स्रोत-आधारित JEE अभ्यास-निर्माता और रूपांतर-परीक्षक की भूमिका निभाएँ।',
    focus: 'create exactly five fresh variants while preserving the exact mathematical structure, intended method and reasoning-demand band',
    focusHi: 'ठीक गणितीय संरचना, अपेक्षित विधि और तर्क-माँग का स्तर बचाते हुए ठीक पाँच नए रूपांतर बनवाना',
    steps: [
      'Extract the invariant concept, method, representation, answer type and difficulty drivers before changing any value.',
      'State a parameter table with allowed ranges, exclusions and degeneracy tests taken from [ALLOWED VALUE RANGES AND EXCLUSIONS].',
      'Generate exactly five distinct items; reject cosmetic rearrangements, changed-skill variants and any item whose reasoning load leaves the source question’s difficulty band.',
      'Solve every accepted item independently and record the check without implying that computation authenticates the source question.',
    ],
    stepsHi: [
      'किसी मान को बदलने से पहले अपरिवर्तित अवधारणा, विधि, निरूपण, उत्तर-प्रकार और कठिनाई-कारक निकालें।',
      '[ALLOWED VALUE RANGES AND EXCLUSIONS] से स्वीकार्य दायरा, अपवाद और विकृत स्थिति की जाँच वाली पैरामीटर-तालिका लिखें।',
      'ठीक पाँच अलग प्रश्न बनाएँ; केवल सतही फेरबदल, कौशल बदलने वाले रूपांतर और स्रोत-प्रश्न के कठिनाई-स्तर से बाहर जाने वाला हर रूपांतर अस्वीकार करें।',
      'हर स्वीकृत प्रश्न को स्वतंत्र रूप से हल करें और जाँच दर्ज करें, पर संगणना को स्रोत-प्रश्न की प्रामाणिकता का प्रमाण न बताएँ।',
    ],
    outputName: 'Variant Bank', outputNameHi: 'रूपांतर संग्रह',
    outputDescription: 'invariant map, parameter rules and five same-difficulty items',
    outputDescriptionHi: 'अपरिवर्तित तत्वों का मानचित्र, पैरामीटर-नियम और समान कठिनाई वाले पाँच अलग प्रश्न',
  },
  {
    title: 'Distractor Autopsy for a Pasted JEE MCQ',
    titleHi: 'पेस्ट किए JEE MCQ के विकल्पों की त्रुटि-जाँच',
    tag: 'Distractor Error Analysis', fmt: 'doc', aud: 'both', extraInput: '[STUDENT RESPONSE PATTERNS]',
    whatYouGet: 'A choice-by-choice distractor analysis tied to the pasted MCQ, including likely reasoning breaks, corrective questions and evidence limits.',
    whatYouGetHi: 'पेस्ट किए MCQ से जुड़ा हर विकल्प का विश्लेषण, जिसमें संभावित तर्क-विच्छेद, सुधारात्मक सवाल और प्रमाण की सीमाएँ हों।',
    howToUse: 'Paste the exact MCQ, options, key and anonymised response pattern; check each diagnosis against student working before teaching from it.',
    howToUseHi: 'ठीक MCQ, विकल्प, उत्तर-कुंजी और गुमनाम उत्तर-रुझान पेस्ट करें; पढ़ाने से पहले हर निदान को विद्यार्थियों के हल से मिलाएँ।',
    commonFix: 'If the analysis guesses student thinking, require an observed-evidence column and label unsupported explanations as hypotheses to test.',
    commonFixHi: 'यदि विश्लेषण विद्यार्थी की सोच का अनुमान लगाए, तो देखे गए प्रमाण का स्तंभ जोड़वाएँ और असमर्थित व्याख्याओं को जाँचने योग्य परिकल्पना लिखवाएँ।',
    role: 'Act as a JEE distractor analyst who distinguishes observed work from hypotheses.',
    roleHi: 'देखे गए हल और परिकल्पना को अलग रखने वाले JEE विकल्प-विश्लेषक की भूमिका निभाएँ।',
    focus: 'explain what each option can reveal without pretending to know why a student selected it',
    focusHi: 'विद्यार्थी ने कोई विकल्प क्यों चुना, यह मान लिए बिना हर विकल्प से मिलने वाले संकेत समझना',
    steps: [
      'Solve the pasted MCQ first and state whether the teacher-supplied key agrees with the mathematical solution.',
      'For every option, identify the exact algebraic, conceptual or reading move that could produce it.',
      'Separate evidence in [STUDENT RESPONSE PATTERNS] from plausible but unobserved hypotheses.',
      'Write one diagnostic follow-up and one corrective micro-task per distractor without labelling a student.',
    ],
    stepsHi: [
      'पहले पेस्ट किए MCQ को हल करें और बताएँ कि शिक्षक की उत्तर-कुंजी गणितीय हल से मेल खाती है या नहीं।',
      'हर विकल्प के लिए वह ठीक बीजगणितीय, अवधारणात्मक या पठन-चरण पहचानें जिससे वह उत्तर मिल सकता है।',
      '[STUDENT RESPONSE PATTERNS] में मौजूद प्रमाण को संभावित पर न देखी गई परिकल्पनाओं से अलग रखें।',
      'विद्यार्थी पर कोई ठप्पा लगाए बिना हर गलत विकल्प के लिए एक निदानात्मक अगला सवाल और एक छोटा सुधारात्मक कार्य लिखें।',
    ],
    outputName: 'Distractor Matrix', outputNameHi: 'विकल्प-विश्लेषण तालिका',
    outputDescription: 'option, possible reasoning break, evidence status and corrective move',
    outputDescriptionHi: 'विकल्प, संभावित तर्क-विच्छेद, प्रमाण की स्थिति और सुधारात्मक कदम',
  },
  {
    title: 'Teacher Marking Scheme from a Pasted PYQ',
    titleHi: 'पेस्ट किए PYQ से शिक्षक अंकन-योजना',
    tag: 'Marking Scheme Builder', fmt: 'pdf-print', aud: 'teacher', extraInput: '[TOTAL MARKS AND PART MARK POLICY]',
    whatYouGet: 'A transparent provisional marking scheme for a pasted question, with method marks, error carry-forward rules and moderation notes.',
    whatYouGetHi: 'पेस्ट किए प्रश्न की पारदर्शी अस्थायी अंकन-योजना, जिसमें विधि-अंक, त्रुटि आगे ले जाने के नियम और समायोजन टिप्पणियाँ हों।',
    howToUse: 'Paste the full question, a separately checked solution and your marks policy; moderate the draft against real scripts before adopting it.',
    howToUseHi: 'पूरा प्रश्न, अलग से जाँचा हल और अपनी अंक-नीति पेस्ट करें; अपनाने से पहले मसौदे को वास्तविक उत्तर-पुस्तिकाओं से मिलाकर समायोजित करें।',
    commonFix: 'If marks reward line count instead of reasoning, ask for each mark to be tied to one observable mathematical achievement.',
    commonFixHi: 'यदि अंक तर्क के बजाय पंक्तियों की संख्या पर मिलें, तो हर अंक को एक दिखाई देने वाली गणितीय उपलब्धि से जोड़ने को कहें।',
    role: 'Act as a cautious JEE marking-scheme designer and moderation assistant.',
    roleHi: 'सावधान JEE अंकन-योजना निर्माता और समायोजन सहायक की भूमिका निभाएँ।',
    focus: 'draft a usable teacher marking scheme without presenting it as an official exam-board scheme',
    focusHi: 'उपयोगी शिक्षक अंकन-योजना बनाना, पर उसे आधिकारिक परीक्षा-संस्था की योजना न बताना',
    steps: [
      'Solve the question independently and reconcile the solution with the teacher-supplied answer before assigning marks.',
      'Break the solution into observable mathematical achievements rather than lines or presentation style.',
      'Allocate [TOTAL MARKS AND PART MARK POLICY] exactly, including alternative valid methods and error carry-forward boundaries.',
      'Add three sample responses at different levels and show a moderation check, all labelled ORIGINAL PRACTICE.',
    ],
    stepsHi: [
      'अंक बाँटने से पहले प्रश्न को स्वतंत्र रूप से हल करें और शिक्षक के दिए उत्तर से समाधान का मिलान करें।',
      'समाधान को पंक्तियों या प्रस्तुति के बजाय दिखाई देने वाली गणितीय उपलब्धियों में बाँटें।',
      'वैकल्पिक सही विधियों और त्रुटि आगे ले जाने की सीमाओं सहित [TOTAL MARKS AND PART MARK POLICY] ठीक-ठीक लागू करें।',
      'अलग स्तरों के तीन नमूना उत्तर और समायोजन-जाँच जोड़ें; सबको ORIGINAL PRACTICE लिखें।',
    ],
    outputName: 'Provisional Marking Scheme', outputNameHi: 'अस्थायी अंकन-योजना',
    outputDescription: 'mark points, alternatives, carry-forward policy and moderation examples',
    outputDescriptionHi: 'अंक-बिंदु, विकल्प, त्रुटि आगे ले जाने की नीति और समायोजन उदाहरण',
  },
  {
    title: 'Similar PYQ-Style Drill with WolframAlpha Self-Checks',
    titleHi: 'WolframAlpha स्वयं-जाँच के साथ समान PYQ-शैली अभ्यास',
    tag: 'Self Check Drill', fmt: 'links', aud: 'both', extraInput: '[DRILL SIZE AND VALUE RANGES]',
    whatYouGet: 'A small ORIGINAL PRACTICE drill modelled on pasted questions, with solved keys and raw WolframAlpha links labelled check this yourself.',
    whatYouGetHi: 'पेस्ट किए प्रश्नों पर आधारित छोटा ORIGINAL PRACTICE अभ्यास, हल की गई उत्तर-कुंजी और check this yourself चिह्न वाली कच्ची WolframAlpha लिंक के साथ।',
    howToUse: 'Paste the source questions and set number ranges; open every generated WolframAlpha link in a browser and inspect its decoded query before release.',
    howToUseHi: 'स्रोत-प्रश्न और संख्या-दायरे पेस्ट करें; जारी करने से पहले हर बनी WolframAlpha लिंक ब्राउज़र में खोलें और उसकी डिकोड की गई क्वेरी जाँचें।',
    commonFix: 'If a link checks a different expression, rebuild it from the final plain-calculator query and compare the decoded text character-for-character.',
    commonFixHi: 'यदि लिंक अलग व्यंजक जाँचे, तो अंतिम साधारण कैलकुलेटर क्वेरी से उसे फिर बनाएँ और डिकोड किए पाठ का अक्षरशः मिलान करें।',
    role: 'Act as a source-bound drill designer and WolframAlpha link auditor.',
    roleHi: 'स्रोत-आधारित अभ्यास-निर्माता और WolframAlpha लिंक-परीक्षक की भूमिका निभाएँ।',
    focus: 'build a similar drill whose answer key can be recomputed through teacher-inspected WolframAlpha links',
    focusHi: 'ऐसा समान अभ्यास बनाना जिसकी उत्तर-कुंजी शिक्षक द्वारा जाँची WolframAlpha लिंक से फिर गणना की जा सके',
    steps: [
      'Extract the common structure from the pasted questions and state exactly what must remain unchanged.',
      'Generate [DRILL SIZE AND VALUE RANGES] items with distinct valid values and no copied past-question wording.',
      'Solve each item first, then construct one percent-encoded plain-calculator WolframAlpha query for its answer check.',
      'Print each raw link and paste fallback on adjacent lines, label it check this yourself and reject any failed round trip.',
    ],
    stepsHi: [
      'पेस्ट किए प्रश्नों से साझा संरचना निकालें और ठीक बताएँ कि कौन-से तत्व अपरिवर्तित रहने चाहिए।',
      'अलग वैध मानों और पिछले प्रश्न की नकल किए बिना [DRILL SIZE AND VALUE RANGES] के अनुसार प्रश्न बनाएँ।',
      'पहले हर प्रश्न हल करें, फिर उसके उत्तर की जाँच के लिए एक प्रतिशत-कूटबद्ध साधारण कैलकुलेटर WolframAlpha क्वेरी बनाएँ।',
      'हर कच्ची लिंक और पेस्ट-विकल्प पास-पास की पंक्तियों में दें, check this yourself लिखें और राउंड-ट्रिप असफल हो तो उसे अस्वीकार करें।',
    ],
    outputName: 'Linked Drill', outputNameHi: 'लिंक वाला अभ्यास',
    outputDescription: 'original items, worked key, decoded query audit and self-check links',
    outputDescriptionHi: 'मौलिक प्रश्न, हल की गई कुंजी, डिकोड क्वेरी की जाँच और स्वयं-जाँच लिंक',
  },
  {
    title: 'Difficulty Progression Ladder from Pasted PYQs',
    titleHi: 'पेस्ट किए PYQ से कठिनाई-प्रगति सीढ़ी',
    tag: 'Progression Ladder', fmt: 'doc', aud: 'teacher', extraInput: '[LADDER LEVELS AND LEARNER START]',
    whatYouGet: 'A prerequisite-to-transfer progression built from the mathematical demands visible in a pasted set, with original bridge tasks and exit checks.',
    whatYouGetHi: 'पेस्ट किए प्रश्न-समूह में दिखाई देने वाली गणितीय माँगों से बनी पूर्वज्ञान से अनुप्रयोग तक प्रगति, मौलिक जोड़ने वाले कार्यों और निकास-जाँच के साथ।',
    howToUse: 'Paste the complete set and learner starting evidence; approve the demand map before assigning the labelled bridge tasks.',
    howToUseHi: 'पूरा प्रश्न-समूह और विद्यार्थी के शुरुआती स्तर का प्रमाण पेस्ट करें; चिह्नित जोड़ने वाले कार्य देने से पहले माँग-मानचित्र स्वीकृत करें।',
    commonFix: 'If levels differ only by larger numbers, require a cognitive-demand table and redesign each rung around a distinct reasoning move.',
    commonFixHi: 'यदि स्तर केवल बड़ी संख्याओं से अलग हों, तो संज्ञानात्मक माँग की तालिका माँगें और हर पायदान को अलग तर्क-चरण के आधार पर फिर बनाएँ।',
    role: 'Act as a JEE learning-progression designer grounded only in pasted questions.',
    roleHi: 'केवल पेस्ट किए प्रश्नों पर आधारित JEE अधिगम-प्रगति निर्माता की भूमिका निभाएँ।',
    focus: 'sequence prerequisites, core moves and transfer without inventing a difficulty trend for the exam',
    focusHi: 'परीक्षा की कठिनाई का रुझान गढ़े बिना पूर्वज्ञान, मुख्य चरण और अनुप्रयोग को क्रम देना',
    steps: [
      'Map the prerequisite, representation, procedure and transfer demands actually visible in the pasted set.',
      'Locate [LADDER LEVELS AND LEARNER START] on that map using only supplied learner evidence.',
      'Create one ORIGINAL PRACTICE bridge task per rung with an explicit reason for its placement.',
      'Add an exit check and decision rule before the learner advances; do not equate number size with difficulty.',
    ],
    stepsHi: [
      'पेस्ट किए प्रश्न-समूह में सचमुच दिखने वाली पूर्वज्ञान, निरूपण, प्रक्रिया और अनुप्रयोग की माँगों का मानचित्र बनाएँ।',
      'केवल दिए विद्यार्थी-प्रमाण से [LADDER LEVELS AND LEARNER START] को उस मानचित्र पर रखें।',
      'हर पायदान के लिए एक ORIGINAL PRACTICE जोड़ने वाला कार्य और उसे वहाँ रखने का स्पष्ट कारण दें।',
      'अगले स्तर पर जाने से पहले निकास-जाँच और निर्णय-नियम जोड़ें; संख्या के आकार को कठिनाई न मानें।',
    ],
    outputName: 'Progression Ladder', outputNameHi: 'प्रगति सीढ़ी',
    outputDescription: 'demand map, ordered rungs, bridge tasks and exit rules',
    outputDescriptionHi: 'माँग-मानचित्र, क्रमबद्ध पायदान, जोड़ने वाले कार्य और निकास-नियम',
  },
  {
    title: 'Pasted-Set-Only PYQ Trend Discussion',
    titleHi: 'केवल पेस्ट किए प्रश्न-समूह पर PYQ रुझान-चर्चा',
    tag: 'Bounded Trend Discussion', fmt: 'doc', aud: 'both', extraInput: '[PASTED SET BOUNDARIES]',
    whatYouGet: 'A carefully bounded discussion of recurring features inside the supplied set only, with counts, counterexamples and no forecast masquerading as a trend.',
    whatYouGetHi: 'केवल दिए प्रश्न-समूह के भीतर दोहराने वाली विशेषताओं की सीमित चर्चा, गणना, विपरीत उदाहरण और रुझान के रूप में पेश किए बिना।',
    howToUse: 'Paste the complete set and its boundaries; describe conclusions as observations about this set, never the examination as a whole.',
    howToUseHi: 'पूरा प्रश्न-समूह और उसकी सीमाएँ पेस्ट करें; निष्कर्षों को केवल इसी समूह के अवलोकन बताएँ, पूरी परीक्षा के नहीं।',
    commonFix: 'If the output generalises beyond the evidence, replace every exam-wide statement with a counted within-set observation and its denominator.',
    commonFixHi: 'यदि आउटपुट प्रमाण से आगे सामान्यीकरण करे, तो परीक्षा-व्यापी हर कथन को इसी समूह के गणितीय अवलोकन और उसके हर से बदलें।',
    role: 'Act as a cautious descriptive analyst of a teacher-pasted question set.',
    roleHi: 'शिक्षक द्वारा पेस्ट किए प्रश्न-समूह के सावधान वर्णनात्मक विश्लेषक की भूमिका निभाएँ।',
    focus: 'discuss only patterns observable within the pasted set and explicitly refuse exam-wide trend or prediction claims',
    focusHi: 'केवल पेस्ट किए समूह में दिखने वाले पैटर्न पर चर्चा करना और परीक्षा-व्यापी रुझान या भविष्यवाणी से स्पष्ट इनकार करना',
    steps: [
      'Define [PASTED SET BOUNDARIES], count the supplied questions and state what is missing or uneven.',
      'Code each pasted item by concept, representation, main method and answer type using a reproducible table.',
      'Report counts and denominators for this set only, including exceptions that weaken each apparent recurrence.',
      'Refuse to forecast future questions, weightage or difficulty and propose only a balanced discussion agenda.',
    ],
    stepsHi: [
      '[PASTED SET BOUNDARIES] तय करें, दिए प्रश्न गिनें और जो अनुपस्थित या असंतुलित है उसे बताएँ।',
      'दोहराई जा सकने वाली तालिका में हर पेस्ट प्रश्न को अवधारणा, निरूपण, मुख्य विधि और उत्तर-प्रकार से वर्गीकृत करें।',
      'केवल इसी समूह के लिए गणना और हर दें तथा हर दिखती पुनरावृत्ति को कमजोर करने वाले अपवाद भी शामिल करें।',
      'भविष्य के प्रश्न, अंक-भार या कठिनाई की भविष्यवाणी से इनकार करें और केवल संतुलित चर्चा की रूपरेखा दें।',
    ],
    outputName: 'Bounded Pattern Table', outputNameHi: 'सीमित पैटर्न तालिका',
    outputDescription: 'within-set coding, counts, denominators, exceptions and discussion questions',
    outputDescriptionHi: 'समूह-अंदर वर्गीकरण, गणना, हर, अपवाद और चर्चा-सवाल',
  },
  {
    title: 'Multi-Method Comparison from One Pasted PYQ',
    titleHi: 'एक पेस्ट किए PYQ से बहु-विधि तुलना',
    tag: 'Method Comparison', fmt: 'doc', aud: 'both', extraInput: '[ALLOWED METHODS]',
    whatYouGet: 'Several valid solution routes for the pasted question, compared for assumptions, length, reliability and transfer value without inventing an official preferred method.',
    whatYouGetHi: 'पेस्ट किए प्रश्न की कई सही समाधान-विधियाँ, जिनकी मान्यताओं, लंबाई, विश्वसनीयता और अनुप्रयोग-क्षमता की तुलना हो, बिना आधिकारिक पसंदीदा विधि गढ़े।',
    howToUse: 'Paste one exact question and restrict the allowed methods; verify each route before using the comparison for discussion.',
    howToUseHi: 'एक ठीक प्रश्न पेस्ट करके स्वीकार्य विधियाँ सीमित करें; तुलना को चर्चा में लेने से पहले हर विधि जाँचें।',
    commonFix: 'If two methods are cosmetic rewrites, require different mathematical representations or core lemmas and remove duplicate routes.',
    commonFixHi: 'यदि दो विधियाँ केवल सतही पुनर्लेखन हों, तो अलग गणितीय निरूपण या मुख्य परिणाम माँगें और दोहराई विधियाँ हटाएँ।',
    role: 'Act as a rigorous JEE solution-method comparator.',
    roleHi: 'कठोर JEE समाधान-विधि तुलनाकर्ता की भूमिका निभाएँ।',
    focus: 'compare genuinely different valid methods for the pasted question without claiming an official exam preference',
    focusHi: 'आधिकारिक परीक्षा-पसंद का दावा किए बिना पेस्ट किए प्रश्न की सचमुच अलग सही विधियों की तुलना करना',
    steps: [
      'Solve the question and list domain restrictions, hidden assumptions and the teacher-supplied target answer.',
      'Develop only genuinely different routes permitted by [ALLOWED METHODS], not shortened rewrites of one route.',
      'Check that every route reaches the same valid answer under the same domain.',
      'Compare prerequisites, time, error risk, elegance and transfer, clearly separating judgement from fact.',
    ],
    stepsHi: [
      'प्रश्न हल करें और परिभाषा-क्षेत्र की सीमाएँ, छिपी मान्यताएँ तथा शिक्षक का दिया लक्ष्य-उत्तर लिखें।',
      'केवल [ALLOWED METHODS] में अनुमत सचमुच अलग विधियाँ विकसित करें, एक ही विधि के छोटे पुनर्लेखन नहीं।',
      'जाँचें कि हर विधि उसी परिभाषा-क्षेत्र में उसी वैध उत्तर तक पहुँचती है।',
      'पूर्वज्ञान, समय, त्रुटि-जोखिम, सुंदरता और अनुप्रयोग की तुलना करें तथा निर्णय को तथ्य से साफ अलग रखें।',
    ],
    outputName: 'Method Decision Table', outputNameHi: 'विधि निर्णय-तालिका',
    outputDescription: 'full routes, assumptions, checks and classroom comparison',
    outputDescriptionHi: 'पूरी विधियाँ, मान्यताएँ, जाँच और कक्षा-तुलना',
  },
  {
    title: 'Misconception Repair Clinic from Pasted PYQ Work',
    titleHi: 'पेस्ट किए PYQ हल से भ्रम-सुधार अभ्यास',
    tag: 'Misconception Repair', fmt: 'doc', aud: 'teacher', extraInput: '[ANONYMISED STUDENT WORK]',
    whatYouGet: 'An evidence-led repair sequence from anonymised work on a pasted question, including the first reasoning break, contrast examples and reassessment.',
    whatYouGetHi: 'पेस्ट किए प्रश्न के गुमनाम हल से प्रमाण-आधारित सुधार-क्रम, जिसमें पहला तर्क-विच्छेद, तुलना-उदाहरण और पुनःआकलन हों।',
    howToUse: 'Remove names, paste the question and representative work, then confirm the diagnosis before assigning the repair branch.',
    howToUseHi: 'नाम हटाकर प्रश्न और प्रतिनिधि हल पेस्ट करें, फिर सुधार-शाखा देने से पहले निदान की पुष्टि करें।',
    commonFix: 'If the diagnosis labels the learner, rewrite it as an observable reasoning step and add a question that can confirm or reject it.',
    commonFixHi: 'यदि निदान विद्यार्थी पर ठप्पा लगाए, तो उसे दिखाई देने वाले तर्क-चरण के रूप में लिखें और उसकी पुष्टि या खंडन करने वाला सवाल जोड़ें।',
    role: 'Act as an evidence-led JEE misconception analyst and remediation designer.',
    roleHi: 'प्रमाण-आधारित JEE भ्रम-विश्लेषक और सुधार-निर्माता की भूमिका निभाएँ।',
    focus: 'repair the first observable reasoning break in anonymised work rather than assign a trait to the learner',
    focusHi: 'विद्यार्थी को कोई गुण देने के बजाय गुमनाम हल में दिखाई देने वाले पहले तर्क-विच्छेद को सुधारना',
    steps: [
      'Compare [ANONYMISED STUDENT WORK] line by line with a separately solved reference method.',
      'Name the first observable divergence and distinguish evidence from a hypothesis about its cause.',
      'Create a correct-versus-incorrect contrast, one diagnostic question and two minimal-pair repair items.',
      'Finish with an ORIGINAL PRACTICE transfer item that tests the reasoning without copying surface numbers.',
    ],
    stepsHi: [
      '[ANONYMISED STUDENT WORK] की हर पंक्ति का अलग से हल की गई संदर्भ-विधि से मिलान करें।',
      'पहला दिखाई देने वाला विचलन बताएँ और उसके कारण के प्रमाण को परिकल्पना से अलग करें।',
      'सही बनाम गलत तुलना, एक निदानात्मक सवाल और दो न्यूनतम-अंतर वाले सुधार-प्रश्न बनाएँ।',
      'सतही संख्याएँ न दोहराते हुए तर्क जाँचने वाले ORIGINAL PRACTICE अनुप्रयोग-प्रश्न से समाप्त करें।',
    ],
    outputName: 'Repair Path', outputNameHi: 'सुधार-पथ',
    outputDescription: 'evidence table, diagnostic, contrast, repair items and transfer check',
    outputDescriptionHi: 'प्रमाण-तालिका, निदान, तुलना, सुधार-प्रश्न और अनुप्रयोग-जाँच',
  },
  {
    title: 'Timed Mini-Mock from Teacher-Pasted PYQs',
    titleHi: 'शिक्षक द्वारा पेस्ट किए PYQ से समयबद्ध लघु-मॉक',
    tag: 'Timed Mini Mock', fmt: 'pdf-print', aud: 'teacher', extraInput: '[TIME CAP AND QUESTION MIX]',
    whatYouGet: 'A print-ready mini-mock assembled only from questions the teacher pasted, with transparent selection, timing guidance and a checked key.',
    whatYouGetHi: 'केवल शिक्षक द्वारा पेस्ट किए प्रश्नों से बना प्रिंट-तैयार लघु-मॉक, पारदर्शी चयन, समय-सुझाव और जाँची गई कुंजी के साथ।',
    howToUse: 'Paste the full eligible question pool and define the time cap; review source labels, permissions and the answer key before printing.',
    howToUseHi: 'पूरा योग्य प्रश्न-संग्रह पेस्ट करके समय-सीमा तय करें; प्रिंट से पहले स्रोत-चिह्न, अनुमति और उत्तर-कुंजी जाँचें।',
    commonFix: 'If the paper adds unseen questions, delete them and rebuild solely by selecting from the numbered pasted pool.',
    commonFixHi: 'यदि पेपर ऐसे प्रश्न जोड़ दे जो पेस्ट नहीं किए गए, तो उन्हें हटाएँ और केवल क्रमांकित पेस्ट संग्रह से चुनकर फिर बनाएँ।',
    role: 'Act as a source-preserving JEE mini-mock assembler and key checker.',
    roleHi: 'स्रोत सुरक्षित रखने वाले JEE लघु-मॉक संयोजक और कुंजी-परीक्षक की भूमिका निभाएँ।',
    focus: 'assemble a balanced timed paper without reconstructing or adding any unpasted past question',
    focusHi: 'कोई अपेस्ट पिछला प्रश्न फिर बनाए या जोड़े बिना संतुलित समयबद्ध पेपर तैयार करना',
    steps: [
      'Number the pasted pool and preserve every selected question character-for-character with its teacher-supplied label.',
      'Use [TIME CAP AND QUESTION MIX] to select a transparent mix without claiming it matches a current official pattern.',
      'Estimate time from explicit assumptions and include a teacher-editable allocation, not a universal promise.',
      'Solve and check the paper independently, then separate the student paper, key and source ledger.',
    ],
    stepsHi: [
      'पेस्ट संग्रह को क्रमांक दें और चुने गए हर प्रश्न को शिक्षक के स्रोत-चिह्न सहित अक्षरशः सुरक्षित रखें।',
      'मौजूदा आधिकारिक पैटर्न से मेल का दावा किए बिना [TIME CAP AND QUESTION MIX] से पारदर्शी मिश्रण चुनें।',
      'स्पष्ट मान्यताओं से समय का अनुमान दें और सबके लिए वादा करने के बजाय शिक्षक द्वारा बदली जा सकने वाली समय-सारणी दें।',
      'पेपर को स्वतंत्र रूप से हल और जाँचकर विद्यार्थी-पेपर, कुंजी और स्रोत-विवरण अलग रखें।',
    ],
    outputName: 'Mini-Mock Pack', outputNameHi: 'लघु-मॉक पैक',
    outputDescription: 'student paper, time plan, checked key and source ledger',
    outputDescriptionHi: 'विद्यार्थी-पेपर, समय-योजना, जाँची कुंजी और स्रोत-विवरण',
  },
  {
    title: 'Chapter Skill Map from a Pasted PYQ Set',
    titleHi: 'पेस्ट किए PYQ समूह से अध्याय-कौशल मानचित्र',
    tag: 'Skill Map', fmt: 'doc', aud: 'teacher', extraInput: '[TEACHER-SUPPLIED CHAPTER TAXONOMY]',
    whatYouGet: 'A question-to-skill map for the pasted set, with prerequisites, representations, methods and uncovered areas clearly separated.',
    whatYouGetHi: 'पेस्ट किए समूह का प्रश्न-से-कौशल मानचित्र, जिसमें पूर्वज्ञान, निरूपण, विधियाँ और न शामिल क्षेत्र साफ अलग हों।',
    howToUse: 'Paste the whole set and your chapter taxonomy; inspect uncertain classifications rather than treating the map as official weightage.',
    howToUseHi: 'पूरा समूह और अपनी अध्याय-वर्गीकरण सूची पेस्ट करें; मानचित्र को आधिकारिक अंक-भार मानने के बजाय अनिश्चित वर्गों की जाँच करें।',
    commonFix: 'If one question is forced into one topic, allow primary and supporting skills with quoted evidence from the pasted wording.',
    commonFixHi: 'यदि एक प्रश्न को जबरन एक विषय में रखा जाए, तो पेस्ट किए पाठ के उद्धृत प्रमाण के साथ मुख्य और सहायक दोनों कौशल रखने दें।',
    role: 'Act as a transparent JEE question-to-skill mapper.',
    roleHi: 'पारदर्शी JEE प्रश्न-से-कौशल मानचित्रकार की भूमिका निभाएँ।',
    focus: 'map the supplied questions to teacher-defined skills without inventing exam-wide weightage',
    focusHi: 'परीक्षा-व्यापी अंक-भार गढ़े बिना दिए प्रश्नों को शिक्षक द्वारा तय कौशलों से जोड़ना',
    steps: [
      'Use only [TEACHER-SUPPLIED CHAPTER TAXONOMY] and flag any question that does not fit cleanly.',
      'Assign each pasted item a primary skill, supporting skill, prerequisite, representation and main reasoning move.',
      'Quote the minimum phrase from the pasted item that supports each classification.',
      'List uncovered taxonomy areas as gaps in this pasted set only, not evidence of exam importance.',
    ],
    stepsHi: [
      'केवल [TEACHER-SUPPLIED CHAPTER TAXONOMY] का उपयोग करें और जो प्रश्न साफ फिट न हो उसे चिह्नित करें।',
      'हर पेस्ट प्रश्न को मुख्य कौशल, सहायक कौशल, पूर्वज्ञान, निरूपण और मुख्य तर्क-चरण दें।',
      'हर वर्गीकरण के समर्थन में पेस्ट प्रश्न का न्यूनतम आवश्यक वाक्यांश उद्धृत करें।',
      'न शामिल वर्गों को केवल इस पेस्ट समूह की कमी बताएँ, परीक्षा में महत्त्व का प्रमाण नहीं।',
    ],
    outputName: 'Question-Skill Matrix', outputNameHi: 'प्रश्न-कौशल तालिका',
    outputDescription: 'item coding, evidence phrases, prerequisites and within-set gaps',
    outputDescriptionHi: 'प्रश्न-वर्गीकरण, प्रमाण-वाक्यांश, पूर्वज्ञान और समूह-अंदर की कमियाँ',
  },
  {
    title: 'Prerequisite Bridge Before a Pasted JEE PYQ',
    titleHi: 'पेस्ट किए JEE PYQ से पहले पूर्वज्ञान सेतु',
    tag: 'Prerequisite Bridge', fmt: 'doc', aud: 'both', extraInput: '[LEARNER EVIDENCE AND BRIDGE LENGTH]',
    whatYouGet: 'A short diagnostic and original bridge sequence that prepares a learner for one pasted question without revealing its solution too early.',
    whatYouGetHi: 'छोटा निदान और मौलिक सेतु-क्रम, जो एक पेस्ट प्रश्न के लिए विद्यार्थी को बहुत जल्दी समाधान बताए बिना तैयार करे।',
    howToUse: 'Paste the exact question and learner evidence; give the diagnostic first, then release only the bridge branch indicated by the response.',
    howToUseHi: 'ठीक प्रश्न और विद्यार्थी-प्रमाण पेस्ट करें; पहले निदान दें, फिर उत्तर से संकेतित सेतु-शाखा ही जारी करें।',
    commonFix: 'If the bridge leaks the final method, replace direct parallels with prerequisite micro-tasks and delay the source question until the exit check.',
    commonFixHi: 'यदि सेतु अंतिम विधि बता दे, तो सीधे समान प्रश्नों को पूर्वज्ञान के छोटे कार्यों से बदलें और निकास-जाँच तक स्रोत-प्रश्न रोकें।',
    role: 'Act as a prerequisite diagnostician and scaffold designer for a pasted JEE question.',
    roleHi: 'पेस्ट किए JEE प्रश्न के लिए पूर्वज्ञान निदानकर्ता और सहारा-निर्माता की भूमिका निभाएँ।',
    focus: 'build the shortest evidence-led bridge to the pasted problem without copying or prematurely solving it',
    focusHi: 'पेस्ट प्रश्न की नकल या समय से पहले समाधान किए बिना प्रमाण-आधारित सबसे छोटा सेतु बनाना',
    steps: [
      'Solve the source question privately to identify the smallest prerequisite dependency chain.',
      'Use [LEARNER EVIDENCE AND BRIDGE LENGTH] to write a brief diagnostic with branching decision rules.',
      'Create ORIGINAL PRACTICE micro-tasks for only the failed prerequisite nodes.',
      'End with a transfer check, then return to the untouched pasted question without revealing its answer.',
    ],
    stepsHi: [
      'सबसे छोटी पूर्वज्ञान-निर्भरता शृंखला पहचानने के लिए स्रोत-प्रश्न को निजी रूप से हल करें।',
      '[LEARNER EVIDENCE AND BRIDGE LENGTH] से शाखित निर्णय-नियम वाला छोटा निदान लिखें।',
      'केवल असफल पूर्वज्ञान-बिंदुओं के लिए ORIGINAL PRACTICE छोटे कार्य बनाएँ।',
      'अनुप्रयोग-जाँच से समाप्त करें, फिर उत्तर बताए बिना अपरिवर्तित पेस्ट प्रश्न पर लौटें।',
    ],
    outputName: 'Bridge Sequence', outputNameHi: 'सेतु-क्रम',
    outputDescription: 'dependency chain, diagnostic, branches, micro-tasks and exit check',
    outputDescriptionHi: 'निर्भरता-शृंखला, निदान, शाखाएँ, छोटे कार्य और निकास-जाँच',
  },
  {
    title: 'Assertion-Reason Practice from Pasted PYQs',
    titleHi: 'पेस्ट किए PYQ से कथन-कारण अभ्यास',
    tag: 'Assertion Reason Practice', fmt: 'pdf-print', aud: 'teacher', extraInput: '[CONVERSION COUNT AND OPTION SCHEME]',
    whatYouGet: 'Original assertion-reason items derived from concepts in pasted questions, with truth checks, dependency explanations and a separate key.',
    whatYouGetHi: 'पेस्ट किए प्रश्नों की अवधारणाओं से बने मौलिक कथन-कारण प्रश्न, सत्य-जाँच, निर्भरता-व्याख्या और अलग कुंजी के साथ।',
    howToUse: 'Paste the source questions and your exact option scheme; inspect every truth value and logical connection before printing.',
    howToUseHi: 'स्रोत-प्रश्न और अपनी ठीक विकल्प-योजना पेस्ट करें; प्रिंट से पहले हर सत्य-मान और तार्किक संबंध जाँचें।',
    commonFix: 'If the reason merely repeats the assertion, require an independent proposition and separately test truth and explanatory sufficiency.',
    commonFixHi: 'यदि कारण केवल कथन दोहराए, तो स्वतंत्र प्रतिज्ञप्ति माँगें और सत्यता तथा व्याख्यात्मक पर्याप्तता को अलग-अलग जाँचें।',
    role: 'Act as a logic-aware JEE assertion-reason item designer.',
    roleHi: 'तर्क-सचेत JEE कथन-कारण प्रश्न-निर्माता की भूमिका निभाएँ।',
    focus: 'convert only the mathematical ideas visible in pasted questions into original assertion-reason practice',
    focusHi: 'केवल पेस्ट प्रश्नों में दिखने वाले गणितीय विचारों को मौलिक कथन-कारण अभ्यास में बदलना',
    steps: [
      'Extract propositions that are mathematically meaningful independently of the source wording.',
      'Apply [CONVERSION COUNT AND OPTION SCHEME] exactly and do not imply that the format is a current exam pattern.',
      'Test assertion truth, reason truth and explanatory connection as three separate checks.',
      'Reject ambiguous quantifiers or domain omissions and provide a concise teacher rationale for every option.',
    ],
    stepsHi: [
      'ऐसी प्रतिज्ञप्तियाँ निकालें जो स्रोत की भाषा से स्वतंत्र रूप से गणितीय अर्थ रखती हों।',
      '[CONVERSION COUNT AND OPTION SCHEME] ठीक लागू करें और प्रारूप को मौजूदा परीक्षा-पैटर्न न बताएँ।',
      'कथन की सत्यता, कारण की सत्यता और व्याख्यात्मक संबंध को तीन अलग जाँच की तरह परखें।',
      'अस्पष्ट परिमाणक या परिभाषा-क्षेत्र की कमी वाले प्रश्न अस्वीकार करें और हर विकल्प का संक्षिप्त शिक्षक-कारण दें।',
    ],
    outputName: 'Assertion-Reason Sheet', outputNameHi: 'कथन-कारण पत्रक',
    outputDescription: 'original items, option scheme, truth table and teacher key',
    outputDescriptionHi: 'मौलिक प्रश्न, विकल्प-योजना, सत्य-तालिका और शिक्षक-कुंजी',
  },
  {
    title: 'Numerical-Answer Drill from Pasted JEE Questions',
    titleHi: 'पेस्ट किए JEE प्रश्नों से संख्यात्मक-उत्तर अभ्यास',
    tag: 'Numerical Answer Drill', fmt: 'links', aud: 'both', extraInput: '[ANSWER FORMAT AND TOLERANCE]',
    whatYouGet: 'A source-honest numerical-answer drill with explicit domains, rounding rules, independently solved keys and self-check links.',
    whatYouGetHi: 'स्रोत-स्पष्ट संख्यात्मक-उत्तर अभ्यास, साफ परिभाषा-क्षेत्र, पूर्णांकन नियम, स्वतंत्र रूप से हल कुंजी और स्वयं-जाँच लिंक के साथ।',
    howToUse: 'Paste representative questions and the teacher-set answer format; test every generated value and rounding rule before assignment.',
    howToUseHi: 'प्रतिनिधि प्रश्न और शिक्षक द्वारा तय उत्तर-प्रारूप पेस्ट करें; देने से पहले हर बने मान और पूर्णांकन नियम की जाँच करें।',
    commonFix: 'If answers depend on unstated rounding, add exact forms first and make tolerance a teacher-supplied rule rather than an assumption.',
    commonFixHi: 'यदि उत्तर अनकहे पूर्णांकन पर निर्भर हों, तो पहले ठीक रूप दें और सहनशीलता को अनुमान के बजाय शिक्षक द्वारा दिया नियम बनाएँ।',
    role: 'Act as a JEE numerical-answer practice designer and answer-format auditor.',
    roleHi: 'JEE संख्यात्मक-उत्तर अभ्यास-निर्माता और उत्तर-प्रारूप परीक्षक की भूमिका निभाएँ।',
    focus: 'create original numerical-response practice with unambiguous answer rules and independently recomputable keys',
    focusHi: 'अस्पष्टता-रहित उत्तर-नियम और स्वतंत्र रूप से फिर गणना योग्य कुंजी वाला मौलिक संख्यात्मक अभ्यास बनाना',
    steps: [
      'Extract the numerical-response structure from the pasted items without copying their values or wording.',
      'State domain, units, exact form and [ANSWER FORMAT AND TOLERANCE] before generating any item.',
      'Generate distinct ORIGINAL PRACTICE items and solve each through an independent second route.',
      'Add a percent-encoded WolframAlpha computation check where suitable, with raw query fallback and teacher inspection label.',
    ],
    stepsHi: [
      'पेस्ट प्रश्नों से संख्यात्मक-उत्तर की संरचना निकालें, पर उनके मान या भाषा की नकल न करें।',
      'कोई प्रश्न बनाने से पहले परिभाषा-क्षेत्र, इकाई, ठीक रूप और [ANSWER FORMAT AND TOLERANCE] बताएँ।',
      'अलग ORIGINAL PRACTICE प्रश्न बनाएँ और हर एक को स्वतंत्र दूसरी विधि से हल करें।',
      'जहाँ उपयुक्त हो वहाँ प्रतिशत-कूटबद्ध WolframAlpha संगणना-जाँच, कच्ची क्वेरी का विकल्प और शिक्षक-जाँच चिह्न जोड़ें।',
    ],
    outputName: 'Numerical Drill', outputNameHi: 'संख्यात्मक अभ्यास',
    outputDescription: 'format rules, original items, checked key and computation links',
    outputDescriptionHi: 'प्रारूप-नियम, मौलिक प्रश्न, जाँची कुंजी और संगणना लिंक',
  },
  {
    title: 'Hint Ladder for a Teacher-Pasted PYQ',
    titleHi: 'शिक्षक द्वारा पेस्ट किए PYQ की संकेत-सीढ़ी',
    tag: 'Hint Ladder', fmt: 'doc', aud: 'both', extraInput: '[HINT COUNT AND RELEASE RULE]',
    whatYouGet: 'A graded hint ladder for one pasted question, from orientation to decisive insight, with the complete solution isolated at the end.',
    whatYouGetHi: 'एक पेस्ट प्रश्न की क्रमबद्ध संकेत-सीढ़ी, शुरुआती दिशा से निर्णायक विचार तक, और पूरा समाधान अंत में अलग।',
    howToUse: 'Paste the exact question and choose a release rule; give one hint at a time and require student work before the next.',
    howToUseHi: 'ठीक प्रश्न पेस्ट करके संकेत जारी करने का नियम चुनें; एक बार में एक संकेत दें और अगले से पहले विद्यार्थी का प्रयास लें।',
    commonFix: 'If early hints reveal the method, rewrite them as attention prompts and reserve formulas or substitutions for later rungs.',
    commonFixHi: 'यदि शुरुआती संकेत विधि बता दें, तो उन्हें ध्यान दिलाने वाले सवालों में बदलें और सूत्र या प्रतिस्थापन बाद के पायदानों के लिए रखें।',
    role: 'Act as a Socratic JEE hint-ladder designer.',
    roleHi: 'संवादी JEE संकेत-सीढ़ी निर्माता की भूमिका निभाएँ।',
    focus: 'scaffold the pasted question without revealing its method or answer before the agreed release point',
    focusHi: 'तय जारी-बिंदु से पहले विधि या उत्तर बताए बिना पेस्ट प्रश्न के लिए सहारा देना',
    steps: [
      'Solve the question privately and identify orientation, representation, key relation and execution stages.',
      'Build [HINT COUNT AND RELEASE RULE] so each hint reveals only the next necessary decision.',
      'Add a student action after every hint and a stop condition when independent progress resumes.',
      'Place the checked full solution after a clear teacher-only divider, never inside an early hint.',
    ],
    stepsHi: [
      'प्रश्न को निजी रूप से हल करके दिशा, निरूपण, मुख्य संबंध और क्रियान्वयन चरण पहचानें।',
      '[HINT COUNT AND RELEASE RULE] के अनुसार ऐसी सीढ़ी बनाएँ जिसमें हर संकेत केवल अगला आवश्यक निर्णय खोले।',
      'हर संकेत के बाद विद्यार्थी-कार्य और स्वतंत्र प्रगति शुरू होने पर रुकने का नियम जोड़ें।',
      'जाँचा पूरा समाधान साफ शिक्षक-मात्र विभाजक के बाद रखें, किसी शुरुआती संकेत में नहीं।',
    ],
    outputName: 'Hint Ladder', outputNameHi: 'संकेत-सीढ़ी',
    outputDescription: 'release rules, graded hints, student actions and isolated full solution',
    outputDescriptionHi: 'जारी-नियम, क्रमबद्ध संकेत, विद्यार्थी-कार्य और अलग पूरा समाधान',
  },
  {
    title: 'Error-Spotting Worksheet from Pasted PYQs',
    titleHi: 'पेस्ट किए PYQ से त्रुटि-पहचान Worksheet',
    tag: 'Error Spotting Sheet', fmt: 'pdf-print', aud: 'teacher', extraInput: '[ERROR TYPES AND ITEM COUNT]',
    whatYouGet: 'A print-ready worksheet of plausible but fictional solution errors based on pasted concepts, with diagnosis prompts and a checked teacher key.',
    whatYouGetHi: 'पेस्ट अवधारणाओं पर आधारित संभावित पर काल्पनिक समाधान-त्रुटियों की प्रिंट-तैयार Worksheet, निदान सवाल और जाँची शिक्षक-कुंजी के साथ।',
    howToUse: 'Paste the source items and name the error types to practise; ensure fictional work is never attributed to a real candidate.',
    howToUseHi: 'स्रोत-प्रश्न और अभ्यास के त्रुटि-प्रकार पेस्ट करें; काल्पनिक हल को कभी किसी वास्तविक परीक्षार्थी से न जोड़ें।',
    commonFix: 'If an error is impossible or too obvious, require a valid reasoning path up to one precise break and a corrected continuation.',
    commonFixHi: 'यदि त्रुटि असंभव या बहुत साफ हो, तो एक ठीक विच्छेद तक वैध तर्क-पथ और उसके बाद सही क्रम माँगें।',
    role: 'Act as a mathematically rigorous error-spotting worksheet designer.',
    roleHi: 'गणितीय रूप से कठोर त्रुटि-पहचान Worksheet निर्माता की भूमिका निभाएँ।',
    focus: 'create fictional error cases from pasted concepts while keeping all source and student claims honest',
    focusHi: 'स्रोत और विद्यार्थी संबंधी दावे ईमानदार रखते हुए पेस्ट अवधारणाओं से काल्पनिक त्रुटि-मामले बनाना',
    steps: [
      'Identify valid solution paths and the precise points where [ERROR TYPES AND ITEM COUNT] can occur.',
      'Write fictional work that is correct until one diagnostically useful break; do not mimic named student work.',
      'Ask learners to locate, explain and repair the first error before finishing the solution.',
      'Provide a teacher key with the first break, misconception hypothesis, corrected line and transfer question.',
    ],
    stepsHi: [
      'वैध समाधान-पथ और वे ठीक बिंदु पहचानें जहाँ [ERROR TYPES AND ITEM COUNT] के अनुसार त्रुटियाँ हो सकती हैं।',
      'ऐसा काल्पनिक हल लिखें जो एक निदान-योग्य विच्छेद तक सही हो; किसी नामित विद्यार्थी के हल की नकल न करें।',
      'विद्यार्थियों से समाधान पूरा करने से पहले पहली त्रुटि खोजने, समझाने और सुधारने को कहें।',
      'पहला विच्छेद, भ्रम-परिकल्पना, सुधरी पंक्ति और अनुप्रयोग-प्रश्न वाली शिक्षक-कुंजी दें।',
    ],
    outputName: 'Error-Spotting Worksheet', outputNameHi: 'त्रुटि-पहचान Worksheet',
    outputDescription: 'fictional worked cases, student prompts and checked teacher key',
    outputDescriptionHi: 'काल्पनिक हल-मामले, विद्यार्थी सवाल और जाँची शिक्षक-कुंजी',
  },
  {
    title: 'Revision Carousel from a Pasted PYQ Set',
    titleHi: 'पेस्ट किए PYQ समूह से पुनरावृत्ति चक्र',
    tag: 'Revision Carousel', fmt: 'interactive', aud: 'teacher', extraInput: '[STATION COUNT AND MINUTES]',
    whatYouGet: 'A classroom station carousel using only the pasted set and clearly labelled original support tasks, with timing, roles and answer checks.',
    whatYouGetHi: 'केवल पेस्ट समूह और साफ चिह्नित मौलिक सहायक कार्यों वाला कक्षा-स्टेशन चक्र, समय, भूमिकाएँ और उत्तर-जाँच के साथ।',
    howToUse: 'Paste the eligible questions, choose station count and time, then print the separate station cards and teacher key.',
    howToUseHi: 'योग्य प्रश्न पेस्ट करके स्टेशन संख्या और समय चुनें, फिर अलग स्टेशन कार्ड और शिक्षक-कुंजी प्रिंट करें।',
    commonFix: 'If one station is overloaded, rebalance by estimated reasoning moves and keep the source questions unchanged.',
    commonFixHi: 'यदि किसी स्टेशन पर अधिक भार हो, तो अनुमानित तर्क-चरणों से संतुलन बदलें और स्रोत-प्रश्न अपरिवर्तित रखें।',
    role: 'Act as a JEE revision-station planner and source-preserving editor.',
    roleHi: 'JEE पुनरावृत्ति-स्टेशन योजनाकार और स्रोत-सुरक्षित संपादक की भूमिका निभाएँ।',
    focus: 'turn the pasted set into an active revision rotation without silently adding supposed past questions',
    focusHi: 'कथित पिछले प्रश्न चुपचाप जोड़े बिना पेस्ट समूह को सक्रिय पुनरावृत्ति चक्र में बदलना',
    steps: [
      'Sort the numbered pasted questions by concept and estimated reasoning load without changing their wording.',
      'Apply [STATION COUNT AND MINUTES] and assign a clear learner role, product and rotation rule to each station.',
      'Add only ORIGINAL PRACTICE support cards where a prerequisite or reflection task is needed.',
      'Create a teacher timing map, checked key, rapid observation checklist and no-device fallback.',
    ],
    stepsHi: [
      'क्रमांकित पेस्ट प्रश्नों को भाषा बदले बिना अवधारणा और अनुमानित तर्क-भार से बाँटें।',
      '[STATION COUNT AND MINUTES] लागू करके हर स्टेशन को साफ विद्यार्थी-भूमिका, उत्पाद और घुमाव-नियम दें।',
      'जहाँ पूर्वज्ञान या चिंतन-कार्य चाहिए, वहाँ केवल ORIGINAL PRACTICE सहायक कार्ड जोड़ें।',
      'शिक्षक समय-मानचित्र, जाँची कुंजी, त्वरित अवलोकन सूची और बिना उपकरण का विकल्प बनाएँ।',
    ],
    outputName: 'Carousel Plan', outputNameHi: 'पुनरावृत्ति चक्र योजना',
    outputDescription: 'station cards, rotation map, learner roles, key and fallback',
    outputDescriptionHi: 'स्टेशन कार्ड, घुमाव-मानचित्र, विद्यार्थी भूमिकाएँ, कुंजी और विकल्प',
  },
  {
    title: 'Oral Viva Sequence from One Pasted PYQ',
    titleHi: 'एक पेस्ट किए PYQ से मौखिक प्रश्न-क्रम',
    tag: 'Oral Viva Sequence', fmt: 'interactive', aud: 'both', extraInput: '[VIVA LENGTH AND RESPONSE MODE]',
    whatYouGet: 'A responsive oral-question sequence around a pasted problem, with probes, follow-ups, evidence cues and a fair scoring guide.',
    whatYouGetHi: 'पेस्ट प्रश्न के इर्द-गिर्द उत्तर-अनुसार बदलता मौखिक सवाल-क्रम, जाँच-सवाल, अगले सवाल, प्रमाण-संकेत और निष्पक्ष अंक-मार्गदर्शिका के साथ।',
    howToUse: 'Paste one exact question and set the response mode; ask probes without leading, record evidence and disclose that generated follow-ups are original.',
    howToUseHi: 'एक ठीक प्रश्न पेस्ट करके उत्तर-प्रकार तय करें; संकेत दिए बिना जाँच-सवाल पूछें, प्रमाण दर्ज करें और बताएँ कि बने अगले सवाल मौलिक हैं।',
    commonFix: 'If prompts cue the answer, replace them with requests to justify, represent, test a case or compare methods.',
    commonFixHi: 'यदि सवाल उत्तर का संकेत दें, तो उन्हें औचित्य, निरूपण, उदाहरण-जाँच या विधि-तुलना माँगने वाले सवालों से बदलें।',
    role: 'Act as a fair JEE oral-questioning designer and evidence recorder.',
    roleHi: 'निष्पक्ष JEE मौखिक सवाल-निर्माता और प्रमाण-दर्जकर्ता की भूमिका निभाएँ।',
    focus: 'probe reasoning around the pasted question without leading the learner or implying an official viva format',
    focusHi: 'विद्यार्थी को दिशा दिए या आधिकारिक मौखिक प्रारूप का संकेत दिए बिना पेस्ट प्रश्न के तर्क की जाँच करना',
    steps: [
      'Identify the claims, representations and decisions a learner could explain without solving a different problem.',
      'Build [VIVA LENGTH AND RESPONSE MODE] with neutral opening, clarification, justification and transfer probes.',
      'Write branching follow-ups for correct, partial and uncertain responses without disclosing the next step.',
      'Score observable mathematical evidence only and label every generated extension ORIGINAL PRACTICE.',
    ],
    stepsHi: [
      'वे दावे, निरूपण और निर्णय पहचानें जिन्हें विद्यार्थी अलग प्रश्न हल किए बिना समझा सकता है।',
      '[VIVA LENGTH AND RESPONSE MODE] के अनुसार तटस्थ शुरुआत, स्पष्टीकरण, औचित्य और अनुप्रयोग-जाँच बनाएँ।',
      'सही, आंशिक और अनिश्चित उत्तरों के लिए अगला चरण बताए बिना शाखित अगले सवाल लिखें।',
      'केवल दिखाई देने वाले गणितीय प्रमाण को अंक दें और हर बने विस्तार को ORIGINAL PRACTICE लिखें।',
    ],
    outputName: 'Viva Script', outputNameHi: 'मौखिक सवाल-पटकथा',
    outputDescription: 'neutral probes, branches, evidence cues and scoring guide',
    outputDescriptionHi: 'तटस्थ जाँच-सवाल, शाखाएँ, प्रमाण-संकेत और अंक-मार्गदर्शिका',
  },
  {
    title: 'Peer Discussion Protocol for a Pasted PYQ',
    titleHi: 'पेस्ट किए PYQ की सहपाठी चर्चा-प्रक्रिया',
    tag: 'Peer Discussion Protocol', fmt: 'interactive', aud: 'both', extraInput: '[GROUP SIZE AND DISCUSSION TIME]',
    whatYouGet: 'A structured peer-discussion routine for one pasted question, with private commitment, comparison prompts, evidence rules and synthesis.',
    whatYouGetHi: 'एक पेस्ट प्रश्न की संरचित सहपाठी चर्चा, जिसमें निजी उत्तर, तुलना-सवाल, प्रमाण-नियम और निष्कर्ष हों।',
    howToUse: 'Paste the question, set group size and time, then require an individual attempt before any group discussion.',
    howToUseHi: 'प्रश्न पेस्ट करके समूह-आकार और समय तय करें, फिर समूह चर्चा से पहले व्यक्तिगत प्रयास अनिवार्य करें।',
    commonFix: 'If confident voices dominate, add silent writing, rotating roles and an evidence round where every learner contributes one claim.',
    commonFixHi: 'यदि आत्मविश्वासी आवाज़ें हावी हों, तो मौन लेखन, बदलती भूमिकाएँ और हर विद्यार्थी के एक दावे वाला प्रमाण-दौर जोड़ें।',
    role: 'Act as an equitable JEE peer-discussion facilitator.',
    roleHi: 'समान अवसर देने वाले JEE सहपाठी-चर्चा संचालक की भूमिका निभाएँ।',
    focus: 'structure mathematical disagreement around the pasted question while keeping every generated extension clearly original',
    focusHi: 'हर बने विस्तार को साफ मौलिक रखते हुए पेस्ट प्रश्न पर गणितीय असहमति की संरचना बनाना',
    steps: [
      'Create a private commit step so every learner records an initial claim and reason.',
      'Use [GROUP SIZE AND DISCUSSION TIME] to assign rotating explainer, checker, sceptic and recorder roles.',
      'Write prompts that demand comparison of assumptions, representations and checks rather than answer voting.',
      'End with an individual revised response and a class synthesis that distinguishes consensus from proof.',
    ],
    stepsHi: [
      'निजी उत्तर चरण बनाएँ ताकि हर विद्यार्थी अपना शुरुआती दावा और कारण दर्ज करे।',
      '[GROUP SIZE AND DISCUSSION TIME] के अनुसार बदलती समझाने वाला, जाँचकर्ता, प्रश्नकर्ता और लेखक भूमिकाएँ दें।',
      'उत्तर पर मतदान के बजाय मान्यताओं, निरूपण और जाँच की तुलना माँगने वाले सवाल लिखें।',
      'व्यक्तिगत संशोधित उत्तर और ऐसा कक्षा-निष्कर्ष लें जो सहमति को प्रमाण से अलग रखे।',
    ],
    outputName: 'Discussion Protocol', outputNameHi: 'चर्चा-प्रक्रिया',
    outputDescription: 'individual commit, roles, evidence prompts and synthesis',
    outputDescriptionHi: 'व्यक्तिगत उत्तर, भूमिकाएँ, प्रमाण-सवाल और निष्कर्ष',
  },
  {
    title: 'Cross-Difficulty Transfer Pair from Pasted PYQs',
    titleHi: 'पेस्ट किए PYQ से कठिनाई-पार अनुप्रयोग जोड़ी',
    tag: 'Transfer Pair', fmt: 'doc', aud: 'teacher', extraInput: '[SOURCE PAIR AND TARGET GAP]',
    whatYouGet: 'A transparent comparison of two pasted questions plus original bridge and transfer tasks that isolate the reasoning gap between them.',
    whatYouGetHi: 'दो पेस्ट प्रश्नों की पारदर्शी तुलना तथा उनके बीच तर्क-अंतर अलग करने वाले मौलिक सेतु और अनुप्रयोग कार्य।',
    howToUse: 'Paste both complete questions and define the learner gap; verify that the bridge changes one demand at a time.',
    howToUseHi: 'दोनों पूरे प्रश्न पेस्ट करके विद्यार्थी-अंतर तय करें; जाँचें कि सेतु एक बार में केवल एक माँग बदलता है।',
    commonFix: 'If the bridge jumps too far, insert a task that changes only representation, condition or reasoning depth while holding the rest fixed.',
    commonFixHi: 'यदि सेतु बहुत लंबी छलाँग लगाए, तो ऐसा कार्य जोड़ें जो बाकी तत्व स्थिर रखकर केवल निरूपण, शर्त या तर्क-गहराई बदले।',
    role: 'Act as a JEE transfer-task designer and cognitive-demand comparator.',
    roleHi: 'JEE अनुप्रयोग-कार्य निर्माता और संज्ञानात्मक माँग तुलनाकर्ता की भूमिका निभाएँ।',
    focus: 'explain and bridge the reasoning gap between two pasted questions without assigning official difficulty labels',
    focusHi: 'आधिकारिक कठिनाई-चिह्न दिए बिना दो पेस्ट प्रश्नों के तर्क-अंतर को समझाना और पाटना',
    steps: [
      'Analyse [SOURCE PAIR AND TARGET GAP] by prerequisite, representation, constraints, method choice and proof burden.',
      'State which difficulty judgements are evidence-based and which are teacher judgements.',
      'Create two ORIGINAL PRACTICE bridge tasks that change one cognitive demand at a time.',
      'Add an unseen transfer task and a rubric for recognising structure rather than memorising the source pair.',
    ],
    stepsHi: [
      '[SOURCE PAIR AND TARGET GAP] का पूर्वज्ञान, निरूपण, शर्त, विधि-चयन और प्रमाण-भार से विश्लेषण करें।',
      'बताएँ कि कौन-से कठिनाई-निर्णय प्रमाण पर और कौन-से शिक्षक के निर्णय पर आधारित हैं।',
      'एक बार में एक संज्ञानात्मक माँग बदलने वाले दो ORIGINAL PRACTICE सेतु-कार्य बनाएँ।',
      'अनदेखा अनुप्रयोग-कार्य और स्रोत-जोड़ी याद करने के बजाय संरचना पहचानने की रूब्रिक जोड़ें।',
    ],
    outputName: 'Transfer Bridge', outputNameHi: 'अनुप्रयोग सेतु',
    outputDescription: 'demand comparison, two bridge tasks, transfer task and rubric',
    outputDescriptionHi: 'माँग-तुलना, दो सेतु-कार्य, अनुप्रयोग-कार्य और रूब्रिक',
  },
  {
    title: 'Solution-Quality Rubric for Pasted PYQ Responses',
    titleHi: 'पेस्ट किए PYQ उत्तरों की समाधान-गुणवत्ता रूब्रिक',
    tag: 'Solution Quality Rubric', fmt: 'doc', aud: 'teacher', extraInput: '[ANONYMISED RESPONSES AND RUBRIC SCALE]',
    whatYouGet: 'A response-quality rubric grounded in a pasted question and anonymised scripts, separating correctness, reasoning, notation and communication.',
    whatYouGetHi: 'पेस्ट प्रश्न और गुमनाम उत्तरों पर आधारित समाधान-गुणवत्ता रूब्रिक, जिसमें शुद्धता, तर्क, संकेत-लेखन और संप्रेषण अलग हों।',
    howToUse: 'Paste the question, checked solution and anonymised responses; trial the rubric on a small sample and moderate disagreements.',
    howToUseHi: 'प्रश्न, जाँचा समाधान और गुमनाम उत्तर पेस्ट करें; रूब्रिक को छोटे नमूने पर आजमाएँ और मतभेद समायोजित करें।',
    commonFix: 'If style overwhelms mathematics, cap presentation weight and tie every descriptor to observable evidence in the response.',
    commonFixHi: 'यदि प्रस्तुति गणित पर हावी हो, तो उसके अंक सीमित करें और हर वर्णन को उत्तर में दिखाई देने वाले प्रमाण से जोड़ें।',
    role: 'Act as a fair JEE response-rubric designer and moderation assistant.',
    roleHi: 'निष्पक्ष JEE उत्तर-रूब्रिक निर्माता और समायोजन सहायक की भूमिका निभाएँ।',
    focus: 'build an evidence-based teacher rubric without presenting it as an official JEE marking standard',
    focusHi: 'उसे आधिकारिक JEE अंकन-मानक बताए बिना प्रमाण-आधारित शिक्षक रूब्रिक बनाना',
    steps: [
      'Solve the pasted question and identify essential mathematical evidence, valid alternatives and unacceptable gaps.',
      'Use [ANONYMISED RESPONSES AND RUBRIC SCALE] to draft observable descriptors at each level.',
      'Score correctness, reasoning, notation and communication separately and prevent double penalties.',
      'Trial the rubric on supplied scripts, record disagreements and revise ambiguous descriptors.',
    ],
    stepsHi: [
      'पेस्ट प्रश्न हल करके आवश्यक गणितीय प्रमाण, सही वैकल्पिक विधियाँ और अस्वीकार्य कमियाँ पहचानें।',
      '[ANONYMISED RESPONSES AND RUBRIC SCALE] से हर स्तर के दिखाई देने वाले वर्णन बनाएँ।',
      'शुद्धता, तर्क, संकेत-लेखन और संप्रेषण को अलग अंक दें तथा दोहरा दंड रोकें।',
      'दी उत्तर-पुस्तिकाओं पर रूब्रिक आजमाएँ, मतभेद दर्ज करें और अस्पष्ट वर्णन सुधारें।',
    ],
    outputName: 'Moderated Rubric', outputNameHi: 'समायोजित रूब्रिक',
    outputDescription: 'criteria, level descriptors, trial scores and revision notes',
    outputDescriptionHi: 'मानदंड, स्तर-वर्णन, परीक्षण अंक और संशोधन टिप्पणियाँ',
  },
];

export const ITEMS = REVIEWED_CANDIDATES;
